// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzi0IwcsL-bHVrkB3sRkYzCLppwaKSXs',
    appId: '1:896589233469:web:d9c50869adc795f217d954',
    messagingSenderId: '896589233469',
    projectId: 'task1-735a3',
    authDomain: 'task1-735a3.firebaseapp.com',
    storageBucket: 'task1-735a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDum9ZU426dAvAFDkS-Hxj80vS_wgcr7_M',
    appId: '1:896589233469:android:d87f37f276aa3e3c17d954',
    messagingSenderId: '896589233469',
    projectId: 'task1-735a3',
    storageBucket: 'task1-735a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ROZ00saRUrjr4xnsAD0vN1StJl04W0c',
    appId: '1:896589233469:ios:c38d1c12772e1a1517d954',
    messagingSenderId: '896589233469',
    projectId: 'task1-735a3',
    storageBucket: 'task1-735a3.appspot.com',
    iosClientId: '896589233469-56ti5c6r3obnqqes6op9gsl1l8uv3196.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ROZ00saRUrjr4xnsAD0vN1StJl04W0c',
    appId: '1:896589233469:ios:c38d1c12772e1a1517d954',
    messagingSenderId: '896589233469',
    projectId: 'task1-735a3',
    storageBucket: 'task1-735a3.appspot.com',
    iosClientId: '896589233469-56ti5c6r3obnqqes6op9gsl1l8uv3196.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );
}
